# Generated by Django 2.1.3 on 2019-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.IntegerField(default=0, verbose_name='用例总数')),
                ('case_pass_num', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('case_fail_num', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('case_skip_num', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('api_pass_num', models.IntegerField(default=0, verbose_name='通过api数')),
                ('api_fail_num', models.IntegerField(default=0, verbose_name='失败api数')),
                ('api_error_num', models.IntegerField(default=0, verbose_name='异常api数')),
                ('elapsed_time', models.FloatField(default=0, verbose_name='运行耗时')),
                ('start_time', models.FloatField(verbose_name='创建时间')),
                ('type', models.IntegerField(verbose_name='执行类型')),
                ('project', models.IntegerField(verbose_name='项目id')),
            ],
            options={
                'verbose_name': '数据采集',
                'db_table': 'DataCollection',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, '调试'), (2, '异步'), (3, '定时'), (4, 'auto')], verbose_name='报告类型'),
        ),
    ]
